name: CI

on:
  - pull_request

jobs:
  code:
    name: CI
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Check Commits
        uses: wagoid/commitlint-github-action@v5

      - name: Verify Lint
        run: npm run lint

      - name: Verify Unit Tests
        run: npm run unit

      - name: Verify Build
        run: npm run build

      - name: Send Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
